# Generated by Django 3.1.7 on 2021-03-21 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_url', models.URLField()),
                ('hashed_url', models.CharField(max_length=50)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('creator_IP', models.CharField(default='none', max_length=15)),
                ('expires_after', models.DateField(default=datetime.datetime(2021, 3, 28, 17, 10, 43, 611342))),
                ('expires_after_x_clicks', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UrlHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_id', models.CharField(max_length=10)),
                ('ip_address', models.GenericIPAddressField()),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
