# Generated by Django 3.1.7 on 2021-03-08 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortener", "0003_url_clicks"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="creator_IP",
            field=models.CharField(default="none", max_length=15),
        ),
    ]
