# Generated by Django 3.1.7 on 2021-03-09 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortener", "0004_url_creator_ip"),
    ]

    operations = [
        migrations.AddField(
            model_name="url",
            name="expires_after",
            field=models.DateField(
                default=datetime.datetime(2021, 3, 16, 20, 5, 0, 61009)
            ),
        ),
    ]
