# Generated by Django 3.1.7 on 2021-03-09 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("urlshortener", "0008_auto_20210309_2009"),
    ]

    operations = [
        migrations.AlterField(
            model_name="url",
            name="clicks",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="url",
            name="expires_after",
            field=models.DateField(
                default=datetime.datetime(2021, 3, 16, 21, 17, 57, 125645)
            ),
        ),
        migrations.AlterField(
            model_name="url",
            name="expires_after_x_clicks",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
