# Generated by Django 3.1.7 on 2021-03-21 21:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0021_auto_20210321_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expires_after',
            field=models.DateField(default=datetime.datetime(2021, 3, 28, 21, 24, 8, 421619)),
        ),
        migrations.AlterField(
            model_name='url',
            name='original_url',
            field=models.CharField(max_length=500),
        ),
    ]
