# Generated by Django 3.1.7 on 2021-03-22 22:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0023_auto_20210322_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expires_after',
            field=models.DateField(default=datetime.datetime(2021, 3, 29, 22, 19, 32, 762694)),
        ),
    ]
