# Generated by Django 3.1.7 on 2021-03-23 14:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlshortener', '0024_auto_20210322_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='expires_after',
            field=models.DateField(default=datetime.datetime(2021, 3, 30, 14, 14, 15, 130341)),
        ),
    ]
